/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResetpasswordImport } from './routes/reset_password'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutDashboardBillingImport } from './routes/_layout/dashboard/billing'
import { Route as LayoutDashboardUsersIndexImport } from './routes/_layout/dashboard/users/index'
import { Route as LayoutDashboardRadiologyIndexImport } from './routes/_layout/dashboard/radiology/index'
import { Route as LayoutDashboardProceduresIndexImport } from './routes/_layout/dashboard/procedures/index'
import { Route as LayoutDashboardPharmacyIndexImport } from './routes/_layout/dashboard/pharmacy/index'
import { Route as LayoutDashboardPatientsIndexImport } from './routes/_layout/dashboard/patients/index'
import { Route as LayoutDashboardLabIndexImport } from './routes/_layout/dashboard/lab/index'
import { Route as LayoutDashboardConsumablesIndexImport } from './routes/_layout/dashboard/consumables/index'
import { Route as LayoutDashboardConsultationsIndexImport } from './routes/_layout/dashboard/consultations/index'
import { Route as LayoutDashboardConfigIndexImport } from './routes/_layout/dashboard/config/index'
import { Route as LayoutDashboardAppointmentsIndexImport } from './routes/_layout/dashboard/appointments/index'
import { Route as LayoutDashboardAntenatalIndexImport } from './routes/_layout/dashboard/antenatal/index'
import { Route as LayoutDashboardAdmissionsIndexImport } from './routes/_layout/dashboard/admissions/index'
import { Route as LayoutDashboardUsersUserIdImport } from './routes/_layout/dashboard/users/$userId'
import { Route as LayoutDashboardPatientsPatientIdImport } from './routes/_layout/dashboard/patients/$patientId'
import { Route as LayoutDashboardConfigStoreImport } from './routes/_layout/dashboard/config/store'
import { Route as LayoutDashboardConfigRadiologyImport } from './routes/_layout/dashboard/config/radiology'
import { Route as LayoutDashboardConfigProceduresImport } from './routes/_layout/dashboard/config/procedures'
import { Route as LayoutDashboardConfigLabImport } from './routes/_layout/dashboard/config/lab'
import { Route as LayoutDashboardConfigConsultationImport } from './routes/_layout/dashboard/config/consultation'
import { Route as LayoutDashboardConfigBillingImport } from './routes/_layout/dashboard/config/billing'
import { Route as LayoutDashboardConfigAdmissionsImport } from './routes/_layout/dashboard/config/admissions'
import { Route as LayoutDashboardAppointmentsPatientIdImport } from './routes/_layout/dashboard/appointments/$patientId'
import { Route as LayoutDashboardAdmissionsPatientIdImport } from './routes/_layout/dashboard/admissions/$patientId'

// Create Virtual Routes

const LayoutDashboardIndexLazyImport = createFileRoute('/_layout/dashboard/')()

// Create/Update Routes

const ResetpasswordRoute = ResetpasswordImport.update({
  path: '/reset_password',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutDashboardIndexLazyRoute = LayoutDashboardIndexLazyImport.update({
  path: '/dashboard/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/dashboard/index.lazy').then((d) => d.Route),
)

const LayoutDashboardBillingRoute = LayoutDashboardBillingImport.update({
  path: '/dashboard/billing',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardUsersIndexRoute = LayoutDashboardUsersIndexImport.update({
  path: '/dashboard/users/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardRadiologyIndexRoute =
  LayoutDashboardRadiologyIndexImport.update({
    path: '/dashboard/radiology/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardProceduresIndexRoute =
  LayoutDashboardProceduresIndexImport.update({
    path: '/dashboard/procedures/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardPharmacyIndexRoute =
  LayoutDashboardPharmacyIndexImport.update({
    path: '/dashboard/pharmacy/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardPatientsIndexRoute =
  LayoutDashboardPatientsIndexImport.update({
    path: '/dashboard/patients/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardLabIndexRoute = LayoutDashboardLabIndexImport.update({
  path: '/dashboard/lab/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardConsumablesIndexRoute =
  LayoutDashboardConsumablesIndexImport.update({
    path: '/dashboard/consumables/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardConsultationsIndexRoute =
  LayoutDashboardConsultationsIndexImport.update({
    path: '/dashboard/consultations/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardConfigIndexRoute = LayoutDashboardConfigIndexImport.update(
  {
    path: '/dashboard/config/',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutDashboardAppointmentsIndexRoute =
  LayoutDashboardAppointmentsIndexImport.update({
    path: '/dashboard/appointments/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardAntenatalIndexRoute =
  LayoutDashboardAntenatalIndexImport.update({
    path: '/dashboard/antenatal/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardAdmissionsIndexRoute =
  LayoutDashboardAdmissionsIndexImport.update({
    path: '/dashboard/admissions/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardUsersUserIdRoute = LayoutDashboardUsersUserIdImport.update(
  {
    path: '/dashboard/users/$userId',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutDashboardPatientsPatientIdRoute =
  LayoutDashboardPatientsPatientIdImport.update({
    path: '/dashboard/patients/$patientId',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardConfigStoreRoute = LayoutDashboardConfigStoreImport.update(
  {
    path: '/dashboard/config/store',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutDashboardConfigRadiologyRoute =
  LayoutDashboardConfigRadiologyImport.update({
    path: '/dashboard/config/radiology',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardConfigProceduresRoute =
  LayoutDashboardConfigProceduresImport.update({
    path: '/dashboard/config/procedures',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardConfigLabRoute = LayoutDashboardConfigLabImport.update({
  path: '/dashboard/config/lab',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardConfigConsultationRoute =
  LayoutDashboardConfigConsultationImport.update({
    path: '/dashboard/config/consultation',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardConfigBillingRoute =
  LayoutDashboardConfigBillingImport.update({
    path: '/dashboard/config/billing',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardConfigAdmissionsRoute =
  LayoutDashboardConfigAdmissionsImport.update({
    path: '/dashboard/config/admissions',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardAppointmentsPatientIdRoute =
  LayoutDashboardAppointmentsPatientIdImport.update({
    path: '/dashboard/appointments/$patientId',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardAdmissionsPatientIdRoute =
  LayoutDashboardAdmissionsPatientIdImport.update({
    path: '/dashboard/admissions/$patientId',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/reset_password': {
      id: '/reset_password'
      path: '/reset_password'
      fullPath: '/reset_password'
      preLoaderRoute: typeof ResetpasswordImport
      parentRoute: typeof rootRoute
    }
    '/_layout/dashboard/billing': {
      id: '/_layout/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof LayoutDashboardBillingImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardIndexLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/admissions/$patientId': {
      id: '/_layout/dashboard/admissions/$patientId'
      path: '/dashboard/admissions/$patientId'
      fullPath: '/dashboard/admissions/$patientId'
      preLoaderRoute: typeof LayoutDashboardAdmissionsPatientIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/appointments/$patientId': {
      id: '/_layout/dashboard/appointments/$patientId'
      path: '/dashboard/appointments/$patientId'
      fullPath: '/dashboard/appointments/$patientId'
      preLoaderRoute: typeof LayoutDashboardAppointmentsPatientIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/config/admissions': {
      id: '/_layout/dashboard/config/admissions'
      path: '/dashboard/config/admissions'
      fullPath: '/dashboard/config/admissions'
      preLoaderRoute: typeof LayoutDashboardConfigAdmissionsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/config/billing': {
      id: '/_layout/dashboard/config/billing'
      path: '/dashboard/config/billing'
      fullPath: '/dashboard/config/billing'
      preLoaderRoute: typeof LayoutDashboardConfigBillingImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/config/consultation': {
      id: '/_layout/dashboard/config/consultation'
      path: '/dashboard/config/consultation'
      fullPath: '/dashboard/config/consultation'
      preLoaderRoute: typeof LayoutDashboardConfigConsultationImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/config/lab': {
      id: '/_layout/dashboard/config/lab'
      path: '/dashboard/config/lab'
      fullPath: '/dashboard/config/lab'
      preLoaderRoute: typeof LayoutDashboardConfigLabImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/config/procedures': {
      id: '/_layout/dashboard/config/procedures'
      path: '/dashboard/config/procedures'
      fullPath: '/dashboard/config/procedures'
      preLoaderRoute: typeof LayoutDashboardConfigProceduresImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/config/radiology': {
      id: '/_layout/dashboard/config/radiology'
      path: '/dashboard/config/radiology'
      fullPath: '/dashboard/config/radiology'
      preLoaderRoute: typeof LayoutDashboardConfigRadiologyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/config/store': {
      id: '/_layout/dashboard/config/store'
      path: '/dashboard/config/store'
      fullPath: '/dashboard/config/store'
      preLoaderRoute: typeof LayoutDashboardConfigStoreImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/patients/$patientId': {
      id: '/_layout/dashboard/patients/$patientId'
      path: '/dashboard/patients/$patientId'
      fullPath: '/dashboard/patients/$patientId'
      preLoaderRoute: typeof LayoutDashboardPatientsPatientIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/users/$userId': {
      id: '/_layout/dashboard/users/$userId'
      path: '/dashboard/users/$userId'
      fullPath: '/dashboard/users/$userId'
      preLoaderRoute: typeof LayoutDashboardUsersUserIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/admissions/': {
      id: '/_layout/dashboard/admissions/'
      path: '/dashboard/admissions'
      fullPath: '/dashboard/admissions'
      preLoaderRoute: typeof LayoutDashboardAdmissionsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/antenatal/': {
      id: '/_layout/dashboard/antenatal/'
      path: '/dashboard/antenatal'
      fullPath: '/dashboard/antenatal'
      preLoaderRoute: typeof LayoutDashboardAntenatalIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/appointments/': {
      id: '/_layout/dashboard/appointments/'
      path: '/dashboard/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof LayoutDashboardAppointmentsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/config/': {
      id: '/_layout/dashboard/config/'
      path: '/dashboard/config'
      fullPath: '/dashboard/config'
      preLoaderRoute: typeof LayoutDashboardConfigIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/consultations/': {
      id: '/_layout/dashboard/consultations/'
      path: '/dashboard/consultations'
      fullPath: '/dashboard/consultations'
      preLoaderRoute: typeof LayoutDashboardConsultationsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/consumables/': {
      id: '/_layout/dashboard/consumables/'
      path: '/dashboard/consumables'
      fullPath: '/dashboard/consumables'
      preLoaderRoute: typeof LayoutDashboardConsumablesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/lab/': {
      id: '/_layout/dashboard/lab/'
      path: '/dashboard/lab'
      fullPath: '/dashboard/lab'
      preLoaderRoute: typeof LayoutDashboardLabIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/patients/': {
      id: '/_layout/dashboard/patients/'
      path: '/dashboard/patients'
      fullPath: '/dashboard/patients'
      preLoaderRoute: typeof LayoutDashboardPatientsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/pharmacy/': {
      id: '/_layout/dashboard/pharmacy/'
      path: '/dashboard/pharmacy'
      fullPath: '/dashboard/pharmacy'
      preLoaderRoute: typeof LayoutDashboardPharmacyIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/procedures/': {
      id: '/_layout/dashboard/procedures/'
      path: '/dashboard/procedures'
      fullPath: '/dashboard/procedures'
      preLoaderRoute: typeof LayoutDashboardProceduresIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/radiology/': {
      id: '/_layout/dashboard/radiology/'
      path: '/dashboard/radiology'
      fullPath: '/dashboard/radiology'
      preLoaderRoute: typeof LayoutDashboardRadiologyIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/users/': {
      id: '/_layout/dashboard/users/'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof LayoutDashboardUsersIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LayoutRoute: LayoutRoute.addChildren({
    LayoutDashboardBillingRoute,
    LayoutDashboardIndexLazyRoute,
    LayoutDashboardAdmissionsPatientIdRoute,
    LayoutDashboardAppointmentsPatientIdRoute,
    LayoutDashboardConfigAdmissionsRoute,
    LayoutDashboardConfigBillingRoute,
    LayoutDashboardConfigConsultationRoute,
    LayoutDashboardConfigLabRoute,
    LayoutDashboardConfigProceduresRoute,
    LayoutDashboardConfigRadiologyRoute,
    LayoutDashboardConfigStoreRoute,
    LayoutDashboardPatientsPatientIdRoute,
    LayoutDashboardUsersUserIdRoute,
    LayoutDashboardAdmissionsIndexRoute,
    LayoutDashboardAntenatalIndexRoute,
    LayoutDashboardAppointmentsIndexRoute,
    LayoutDashboardConfigIndexRoute,
    LayoutDashboardConsultationsIndexRoute,
    LayoutDashboardConsumablesIndexRoute,
    LayoutDashboardLabIndexRoute,
    LayoutDashboardPatientsIndexRoute,
    LayoutDashboardPharmacyIndexRoute,
    LayoutDashboardProceduresIndexRoute,
    LayoutDashboardRadiologyIndexRoute,
    LayoutDashboardUsersIndexRoute,
  }),
  ResetpasswordRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/reset_password"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/dashboard/billing",
        "/_layout/dashboard/",
        "/_layout/dashboard/admissions/$patientId",
        "/_layout/dashboard/appointments/$patientId",
        "/_layout/dashboard/config/admissions",
        "/_layout/dashboard/config/billing",
        "/_layout/dashboard/config/consultation",
        "/_layout/dashboard/config/lab",
        "/_layout/dashboard/config/procedures",
        "/_layout/dashboard/config/radiology",
        "/_layout/dashboard/config/store",
        "/_layout/dashboard/patients/$patientId",
        "/_layout/dashboard/users/$userId",
        "/_layout/dashboard/admissions/",
        "/_layout/dashboard/antenatal/",
        "/_layout/dashboard/appointments/",
        "/_layout/dashboard/config/",
        "/_layout/dashboard/consultations/",
        "/_layout/dashboard/consumables/",
        "/_layout/dashboard/lab/",
        "/_layout/dashboard/patients/",
        "/_layout/dashboard/pharmacy/",
        "/_layout/dashboard/procedures/",
        "/_layout/dashboard/radiology/",
        "/_layout/dashboard/users/"
      ]
    },
    "/reset_password": {
      "filePath": "reset_password.tsx"
    },
    "/_layout/dashboard/billing": {
      "filePath": "_layout/dashboard/billing.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/": {
      "filePath": "_layout/dashboard/index.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/admissions/$patientId": {
      "filePath": "_layout/dashboard/admissions/$patientId.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/appointments/$patientId": {
      "filePath": "_layout/dashboard/appointments/$patientId.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/config/admissions": {
      "filePath": "_layout/dashboard/config/admissions.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/config/billing": {
      "filePath": "_layout/dashboard/config/billing.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/config/consultation": {
      "filePath": "_layout/dashboard/config/consultation.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/config/lab": {
      "filePath": "_layout/dashboard/config/lab.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/config/procedures": {
      "filePath": "_layout/dashboard/config/procedures.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/config/radiology": {
      "filePath": "_layout/dashboard/config/radiology.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/config/store": {
      "filePath": "_layout/dashboard/config/store.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/patients/$patientId": {
      "filePath": "_layout/dashboard/patients/$patientId.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/users/$userId": {
      "filePath": "_layout/dashboard/users/$userId.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/admissions/": {
      "filePath": "_layout/dashboard/admissions/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/antenatal/": {
      "filePath": "_layout/dashboard/antenatal/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/appointments/": {
      "filePath": "_layout/dashboard/appointments/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/config/": {
      "filePath": "_layout/dashboard/config/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/consultations/": {
      "filePath": "_layout/dashboard/consultations/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/consumables/": {
      "filePath": "_layout/dashboard/consumables/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/lab/": {
      "filePath": "_layout/dashboard/lab/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/patients/": {
      "filePath": "_layout/dashboard/patients/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/pharmacy/": {
      "filePath": "_layout/dashboard/pharmacy/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/procedures/": {
      "filePath": "_layout/dashboard/procedures/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/radiology/": {
      "filePath": "_layout/dashboard/radiology/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/users/": {
      "filePath": "_layout/dashboard/users/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
