/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutDashboardPatientsImport } from './routes/_layout/dashboard/patients'
import { Route as LayoutDashboardBillingImport } from './routes/_layout/dashboard/billing'
import { Route as LayoutDashboardConfigIndexImport } from './routes/_layout/dashboard/config/index'
import { Route as LayoutDashboardAppointmentsIndexImport } from './routes/_layout/dashboard/appointments/index'
import { Route as LayoutDashboardConfigConsultationImport } from './routes/_layout/dashboard/config/consultation'
import { Route as LayoutDashboardAppointmentsAppointmentIdImport } from './routes/_layout/dashboard/appointments/$appointmentId'

// Create Virtual Routes

const LayoutDashboardIndexLazyImport = createFileRoute('/_layout/dashboard/')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutDashboardIndexLazyRoute = LayoutDashboardIndexLazyImport.update({
  path: '/dashboard/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/dashboard/index.lazy').then((d) => d.Route),
)

const LayoutDashboardPatientsRoute = LayoutDashboardPatientsImport.update({
  path: '/dashboard/patients',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardBillingRoute = LayoutDashboardBillingImport.update({
  path: '/dashboard/billing',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardConfigIndexRoute = LayoutDashboardConfigIndexImport.update(
  {
    path: '/dashboard/config/',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutDashboardAppointmentsIndexRoute =
  LayoutDashboardAppointmentsIndexImport.update({
    path: '/dashboard/appointments/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardConfigConsultationRoute =
  LayoutDashboardConfigConsultationImport.update({
    path: '/dashboard/config/consultation',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardAppointmentsAppointmentIdRoute =
  LayoutDashboardAppointmentsAppointmentIdImport.update({
    path: '/dashboard/appointments/$appointmentId',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/dashboard/billing': {
      id: '/_layout/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof LayoutDashboardBillingImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/patients': {
      id: '/_layout/dashboard/patients'
      path: '/dashboard/patients'
      fullPath: '/dashboard/patients'
      preLoaderRoute: typeof LayoutDashboardPatientsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardIndexLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/appointments/$appointmentId': {
      id: '/_layout/dashboard/appointments/$appointmentId'
      path: '/dashboard/appointments/$appointmentId'
      fullPath: '/dashboard/appointments/$appointmentId'
      preLoaderRoute: typeof LayoutDashboardAppointmentsAppointmentIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/config/consultation': {
      id: '/_layout/dashboard/config/consultation'
      path: '/dashboard/config/consultation'
      fullPath: '/dashboard/config/consultation'
      preLoaderRoute: typeof LayoutDashboardConfigConsultationImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/appointments/': {
      id: '/_layout/dashboard/appointments/'
      path: '/dashboard/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof LayoutDashboardAppointmentsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/config/': {
      id: '/_layout/dashboard/config/'
      path: '/dashboard/config'
      fullPath: '/dashboard/config'
      preLoaderRoute: typeof LayoutDashboardConfigIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LayoutRoute: LayoutRoute.addChildren({
    LayoutDashboardBillingRoute,
    LayoutDashboardPatientsRoute,
    LayoutDashboardIndexLazyRoute,
    LayoutDashboardAppointmentsAppointmentIdRoute,
    LayoutDashboardConfigConsultationRoute,
    LayoutDashboardAppointmentsIndexRoute,
    LayoutDashboardConfigIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/dashboard/billing",
        "/_layout/dashboard/patients",
        "/_layout/dashboard/",
        "/_layout/dashboard/appointments/$appointmentId",
        "/_layout/dashboard/config/consultation",
        "/_layout/dashboard/appointments/",
        "/_layout/dashboard/config/"
      ]
    },
    "/_layout/dashboard/billing": {
      "filePath": "_layout/dashboard/billing.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/patients": {
      "filePath": "_layout/dashboard/patients.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/": {
      "filePath": "_layout/dashboard/index.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/appointments/$appointmentId": {
      "filePath": "_layout/dashboard/appointments/$appointmentId.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/config/consultation": {
      "filePath": "_layout/dashboard/config/consultation.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/appointments/": {
      "filePath": "_layout/dashboard/appointments/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/dashboard/config/": {
      "filePath": "_layout/dashboard/config/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
